# Generated by Django 4.1.5 on 2023-01-31 01:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ridesharing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rideowner',
            name='status',
            field=models.CharField(default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='ride',
            name='status',
            field=models.CharField(default='open', max_length=10),
        ),
        migrations.AlterField(
            model_name='rideowner',
            name='destination',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='rideowner',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rideowner',
            name='vehicle_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ridesharer',
            name='destination',
            field=models.CharField(max_length=50),
        ),
    ]
