# Generated by Django 4.1.5 on 2023-02-02 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ridesharing', '0004_rideowner_driver_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rideowner',
            name='driver_id',
            field=models.IntegerField(null=True),
        ),
    ]
