# Generated by Django 4.1.5 on 2023-02-03 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ridesharing', '0005_alter_rideowner_driver_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rideowner',
            name='shared_by',
        ),
        migrations.AddField(
            model_name='rideowner',
            name='number_requested',
            field=models.PositiveSmallIntegerField(default=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ridesharer',
            name='ride_owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ridesharers', to='ridesharing.rideowner'),
            preserve_default=False,
        ),
    ]
